### ISSUE TITLE
Investigate how to get image uploads working

### ISSUE THREAD

**Issue by matttarantino** [dwilliamson5/CS546_WS_final_project#12]
Will be needed for users and items

**Comment by dwilliamson5** [comment]
Unsplash was recommended by one of the TAs: https://github.com/unsplash/unsplash-js. I registered for a developer account, so we can get api keys.

**Comment by dwilliamson5** [comment]
I don't think you can upload images to unsplash? I didn't see it in their documentation.

I have a student azure account. We can use blob storage as long as we don't go over board with the uploads.
